#!/usr/bin/env bash

# If this variable is set to 1, it will delete databases
# and do other destructive things. Don't do it, man!
MIGN_DEBUG_SETUP=0

if [ $MIGN_DEBUG_SETUP -eq 1 ]; then
  echo -e "\033[0;31mRunning script/setup in debug mode\033[m"
fi

# Ensure that Bundler is installed
if [ -z `command -v bundle` ] ; then
    echo "Installing bundler gem..."
    gem install bundler -v=1.0.22
fi

# Install required gems
echo "Installing required gems..."
bundle install --binstubs

# Cleanup the logs
rm -f log/*

# Check if database.yml exists and create it if it doesn't
if [ ! -f config/database.yml ] ; then
  echo "Couldn't find database.yml. Copying database.yml.example"
  cp config/database.yml.example config/database.yml
fi

# Check if the database user already exists
MIGN_USER=`ruby -ryaml -e "puts YAML::load(File.new('./config/database.yml'))['development']['username']"`
MIGN_PASSWORD=`ruby -ryaml -e "puts YAML::load(File.new('./config/database.yml'))['development']['password']"`
MIGN_DEVELOPMENT_DB=`ruby -ryaml -e "puts YAML::load(File.new('./config/database.yml'))['development']['database']"`
MIGN_TEST_DB=`ruby -ryaml -e "puts YAML::load(File.new('./config/database.yml'))['test']['database']"`

if [ $MIGN_DEBUG_SETUP -eq 1 ]; then
  echo "Dropping databases and the Mign database user"
  psql postgres -c "DROP DATABASE $MIGN_DEVELOPMENT_DB"
  psql postgres -c "DROP DATABASE $MIGN_TEST_DB"
  psql postgres -c "REVOKE ALL PRIVILEGES ON SCHEMA public from $MIGN_USER"
  psql postgres -c "DROP ROLE $MIGN_USER"
fi

# Check for the mign database user and create if it doesn't exist
psql postgres $MIGN_USER -c '' 2>/dev/null
if [ $? -ne 0 ]; then
  echo "Creating the Mign database user"
  psql postgres -c "CREATE ROLE $MIGN_USER LOGIN ENCRYPTED PASSWORD '$MIGN_PASSWORD' NOINHERIT VALID UNTIL 'infinity';" >/dev/null
  psql postgres -c "ALTER ROLE $MIGN_USER CREATEDB;"
else
  echo "Mign database user exists"
fi

# Setup the database
echo "Setting up the database"
bundle exec rake db:setup --trace
bundle exec rake db:migrate --trace

if [ $MIGN_DEBUG_SETUP -eq 1 ]; then
  echo "Removing the mign symlink from ~/.pow"
  rm ~/.pow/mign
fi

# Add Mign to Pow if it's not already there
if [ ! -e ~/.pow/mign ] ; then
  echo "Adding Mign to Pow"
  MIGN_INSTALL_PATH=`pwd`
  ln -s $MIGN_INSTALL_PATH ~/.pow/mign
fi

# Restart the server
echo "Restarting Mign"
touch tmp/restart.txt

echo -e "\033[0;32mSetup is done. Now go to http://mign.dev"